# Generated by Django 3.0.6 on 2021-11-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateShipment',
            fields=[
                ('orderId', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pname', models.CharField(max_length=50)),
                ('pmobile', models.IntegerField()),
                ('paddress', models.CharField(max_length=100)),
                ('ppincode', models.IntegerField()),
                ('pcity', models.CharField(max_length=50)),
                ('pstate', models.CharField(max_length=50)),
                ('pcountry', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=50)),
                ('dmobile', models.IntegerField()),
                ('daddress', models.CharField(max_length=100)),
                ('dcity', models.CharField(max_length=50)),
                ('dstate', models.CharField(max_length=50)),
                ('dpincode', models.IntegerField()),
                ('dcountry', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=50)),
                ('productValue', models.IntegerField()),
                ('weight', models.FloatField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('shippingPrice', models.IntegerField()),
                ('estimateDate', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickScheduled', models.BooleanField(default=True)),
                ('outForPickup', models.BooleanField()),
                ('pickedUp', models.BooleanField()),
                ('transit', models.BooleanField()),
                ('outForDelivery', models.BooleanField()),
                ('delivered', models.BooleanField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippingdjango.CreateShipment')),
            ],
        ),
    ]
