# Generated by Django 3.0.6 on 2021-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingdjango', '0002_auto_20211110_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='outForDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='outForPickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='pickedUp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='transit',
            field=models.BooleanField(default=False),
        ),
    ]
