# Generated by Django 3.0.6 on 2021-11-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingdjango', '0003_auto_20211112_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
