# Generated by Django 3.0.6 on 2021-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingdjango', '0004_tracking_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='undelivered',
            field=models.BooleanField(default=False),
        ),
    ]
